# (c) 2017 DataNexus Inc.  All Rights Reserved
- name: Download zookeeper distribution to /tmp
  become: true
  get_url:
    url: "{{zookeeper_url}}"
    dest: /tmp
    mode: 0644
    validate_certs: no
  environment: "{{environment_vars}}"
- name: Create "{{zookeeper_dir}}"
  become: true
  file:
    path: "{{zookeeper_dir}}"
    state: directory
    owner: storm
    group: storm
- name: Unpack storm distribution into "{{zookeeper_dir}}"
  become: true
  unarchive:
    copy: no
    src: "/tmp/zookeeper-{{zookeeper_version}}.tar.gz"
    dest: "{{zookeeper_dir}}"
    extra_opts: [ "--strip-components=1" ]
    owner: storm
    group: storm
- name: Create apache-zookeeper configuration file
  become: true
  template:
    src: "../templates/zoo.cfg"
    dest: /opt/apache-zookeeper/conf/
    mode: 0644
    
