# (c) 2017 DataNexus Inc.  All Rights Reserved
- name: Download storm distribution to /tmp
  become: true
  get_url:
    url: "{{storm_url}}"
    dest: /tmp
    mode: 0644
    validate_certs: no
  environment: "{{environment_vars}}"
- name: Create "{{storm_dir}}"
  become: true
  file:
    path: "{{storm_dir}}"
    state: directory
    owner: storm
    group: storm
- name: Unpack storm distribution into "{{storm_dir}}"
  become: true
  unarchive:
    copy: no
    src: "/tmp/apache-storm-{{storm_version}}.tar.gz"
    dest: "{{storm_dir}}"
    extra_opts: [ "--strip-components=1" ]
    owner: storm
    group: storm
    
