# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- name: Pause before starting storm nimbus service
  become: true
  command: sleep 10
- name: Start storm nimbus
  become: true
  command: systemctl start storm-nimbus.service
- name: Pause before starting storm supervisor service
  become: true
  command: sleep 10
- name: Start storm supervisor
  become: true
  command: systemctl start storm-supervisor.service
- name: Pause before starting storm ui service
  become: true
  command: sleep 10
- name: Start storm ui service
  become: true
  command: systemctl start storm-ui.service
